apiVersion: v1
kind: Service
metadata:
  name: temp-converter-svc
spec:
  selector:
    app: convert-app 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32000
  type: LoadBalancer
---
