apiVersion: v1
kind: Service
metadata:
  name: app-news-svc
spec:
  selector:
    app: app-news
  ports:
   - port: 80
     targetPort: 8080
     nodePort: 32000
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
   - port: 5432
  type: ClusterIP
    
